# Generated by Django 5.0.7 on 2024-08-03 00:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight_full', models.FloatField(blank=True, null=True)),
                ('weight_partial', models.FloatField(blank=True, null=True)),
                ('weight_none', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OOAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('lider', 'Líder de Criterio'), ('miembro', 'Equipo de Criterio')], max_length=20, null=True)),
                ('can_access_module_a', models.BooleanField(default=False)),
                ('can_access_module_b', models.BooleanField(default=False)),
                ('can_access_module_c', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nomenclatura', models.CharField(help_text='Ejemplo: 1', max_length=10)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider_criterios', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='miembro_criterios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidences/')),
                ('status', models.CharField(blank=True, choices=[('cumple', 'Cumple'), ('parcial', 'Parcial'), ('no_cumple', 'No Cumple')], max_length=10, null=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='myapp.accion')),
            ],
        ),
        migrations.CreateModel(
            name='SubBanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_puntaje', models.FloatField(blank=True, null=True)),
                ('max_puntaje', models.FloatField(blank=True, null=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbandas', to='myapp.banda')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nomenclatura', models.CharField(help_text='Ejemplo: 1.1', max_length=10)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriterios', to='myapp.criterio')),
            ],
        ),
        migrations.AddField(
            model_name='accion',
            name='subcriterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='myapp.subcriterio'),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='unidad_photos/')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('values', models.TextField(blank=True, null=True)),
                ('quality_policy', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('total_trust_staff', models.IntegerField(blank=True, null=True)),
                ('total_union_staff', models.IntegerField(blank=True, null=True)),
                ('ooad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='myapp.ooad')),
            ],
        ),
        migrations.AddField(
            model_name='criterio',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='myapp.unidad'),
        ),
    ]
