# Generated by Django 5.0.7 on 2024-08-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidad',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='total_trust_staff',
            new_name='personal_base',
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='total_union_staff',
            new_name='personal_confianza',
        ),
        migrations.RenameField(
            model_name='unidad',
            old_name='quality_policy',
            new_name='politica_calidad',
        ),
    ]
